<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.15.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.15.1" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.8.0.20230708" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.8.0.20230708" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Yolov5Net.App\Yolov5Net.App.csproj" />
  </ItemGroup>

</Project>